### ISSUE TITLE
CMake Error at CMakeLists.txt:17 (find_package):

### ISSUE THREAD

**Issue by troyBORG** [jketterl/digiham#10]
```
root@OpenWebRX:/home/troyborg/digiham/build# cmake ..
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found suitable version "3.12.4", minimum required is "3.0")
CMake Error at CMakeLists.txt:17 (find_package):
  By not providing "Findcsdr.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "csdr", but
  CMake did not find one.

  Could not find a package configuration file provided by "csdr" (requested
  version 0.18) with any of the following names:

    csdrConfig.cmake
    csdr-config.cmake

  Add the installation prefix of "csdr" to CMAKE_PREFIX_PATH or set
  "csdr_DIR" to a directory containing one of the above files.  If "csdr"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/troyborg/digiham/build/CMakeFiles/CMakeOutput.log".
See also "/home/troyborg/digiham/build/CMakeFiles/CMakeError.log".
```
root@OpenWebRX:/home/troyborg# whereis csdr
csdr: /usr/bin/csdr /usr/local/bin/csdr

why can't it find it?

**Comment by troyBORG** [comment]
root@OpenWebRX:/home/troyborg# whereis csdr
csdr: /usr/bin/csdr /usr/local/bin/csdr

why can't it find it?

**Comment by troyBORG** [comment]
```
root@OpenWebRX:/home/troyborg/csdr/build/src# ls
CMakeFiles           csdr    CsdrConfig.cmake         csdr.pc  libcsdr.so         Makefile
cmake_install.cmake  csdr++  CsdrConfigVersion.cmake  lib      libcsdr.so.0.18.1  nmux
```

I found this `CsdrConfig.cmake` file it wants?  Where does it want it place?

**Comment by jketterl** [comment]
It should be installed during the `make install` step of csdr. You do seem to have multiple installs of csdr on your system though, and since I don't know how you ended up there, it's hard to tell what should be where.

- When manually compiling csdr (without any additional parameters) the files should end up in the `/usr/local` prefix. This would correspond to your `/usr/local/bin/csdr` binary. The expected location in that case would be `/usr/local/lib/cmake/Csdr`. Depending on your distribution, this constellation may require additional cmake configuration since some distributions seem to not include that path in their default cmake search path.
- When installing from packages, the files should end up in the `/usr` prefix. This would correspond to your `/usr/bin/csdr` binary. The common practice on many distributions is to split off any development files into a separate package with a `-dev` suffix. There should be a `libcsdr-dev` package available that contains the files you're looking for.

Whichever way you chose, I would additionally recommend to clean up your system since having two installations is bound to cause further issues down the line.

Also, if you're installing from packages, you should have a `digiham` package available to you, so depending on what you're trying to achieve, compiling from source may not even be necessary.

Lastly, we have a mailing list available for general support at https://groups.io/g/openwebrx

Closing since this is not an issue with csdr.
