### ISSUE TITLE
DMR Decode

### ISSUE THREAD

**Issue by alwinhb** [jketterl/digiham#12]
How can I decode a DMR Audio? Using this code?

**Comment by jketterl** [comment]
This code gives you the basic building blocks to decode a DMR signal. You can check the examples folder, there is some basic pipelines in there that work. You will however need an instance of [codecserver](https://github.com/jketterl/codecserver) that has been configured to handle the AMBE voice codec data that is used in DMR.

Please also refer to this FAQ: https://github.com/jketterl/openwebrx/wiki/Troubleshooting---FAQ#my-openwebrx-installation-is-still-missing-dmr--ysf--d-star-and-nxdn

Closing since this is not an issue with the software. Please use the mailing list for questions and support requests.

**Comment by alwinhb** [comment]
@jketterl Thanks for the quick update, Can it decode a Data Sample as well? I have few of the hex data burst samples with me.
